### ISSUE TITLE
Optimize Cardano memory usage

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/trezor-firmware#41]
After Shelley update the memory usage was not optimized as foreseen in https://github.com/trezor/trezor-firmware/issues/94 which means that there is still a pretty low limit to the maximum tx size - as far as we tested, between 20-25 tx inputs would work at maximum or for stake pool registration 20-25 owners, which is far less than the maximum theoretical Cardano tx size (16kB).

Actionables:
1) document this known bug in trezor-connect docs
2) investigate how the memory usage can be optimized - seems like it's failing during CBOR serialization

**Comment by gabrielKerekes** [comment]
Resolved by transaction streaming.
