### ISSUE TITLE
Fix metadata validation

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/trezor-firmware#54]
Currently, Trezor enforces the tx metadata to be a valid CBOR dict which isn't accurate anymore as the format has been extended to be an array as well

Current Trezor code: https://github.com/vacuumlabs/trezor-firmware/blob/10edcb0d3adbd8ff524133c2671f34f9dc085e8c/core/src/apps/cardano/sign_tx.py#L315

New CDDL: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl

Proposed fix: relax the validation of metadata to only be a valid CBOR

We may consider reworking the serialized tx format to return the unsigned serialized tx body, witnesses and serialized metadata separately and have trezor connect/cli assemble the full transaction separately and we could remove metadata validation completely then as the original concern was CBOR-injection within Trezor should the tx format change in the future: https://github.com/trezor/trezor-firmware/pull/1145#discussion_r462124445

**Comment by gabrielKerekes** [comment]
The validation has been removed as part of [Catalyst update](https://github.com/trezor/trezor-firmware/pull/1564/files#diff-449dbb3cc07455194600fd241faad462fb0b7417008b0b99fef57c4c7966745bR65).
