### ISSUE TITLE
Reintroduce utxo max size limitation

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/trezor-firmware#58]
Despite the max tx size being around 9kB now, if max utxo size is raised from 4kB at protocol level (https://github.com/input-output-hk/cardano-ledger-specs/pull/2099) Trezor may again face issues with producing utxos it wouldn't be able to spend later on.

**Comment by gabrielKerekes** [comment]
Added back into the code as part of https://github.com/trezor/trezor-firmware/pull/1606. It will however be removed again with transaction streaming.
